apiVersion: v1
kind: Secret
metadata:
  name: mongo-uri
  namespace: whiteboard
type: Opaque
stringData:
  MONGO_URI: "mongodb+srv://aks85_db_user:YfsITla0KkaDjZXo@cluster0.wzvkhka.mongodb.net/whiteboard-metadata-db?appName=Cluster0&retryWrites=true&w=majority"

