apiVersion: v1
kind: Secret
metadata:
  name: mongo-uri
  namespace: whiteboard
type: Opaque
stringData:
  MONGO_URI: "mongodb+srv://snapshot-aggregator:PASSWORD@whiteboard-cluster.mongodb.net/whiteboard?retryWrites=true&w=majority"

